apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argocd-demo-pipeline-
spec:
  entrypoint: deploy
  templates:
  - name: deploy
    steps:
    - - name: deploy-app
        template: deploy-app
        arguments:
          parameters:
          - name: app-name
            value: my-app
          - name: app-image
            value: my-registry/my-app:latest
          - name: app-env
            value: dev
          - name: app-replicas
            value: "3"
  - name: deploy-app
    inputs:
      parameters:
      - name: app-name
      - name: app-image
      - name: app-env
      - name: app-replicas
    container:
      image: my-deploy-image
      command: [sh, -c]
      args: ["echo Deploying $app-name image $app-image in environment $app-env with $app-replicas replicas."]