apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: general
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: mssql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true